In [1]:
#we may need some code in the ../python directory and/or matplotlib styles
import sys
sys.path.append('../python/')

#matplotlib for plotting
import matplotlib as mpl
from matplotlib import pyplot as plt
plt.style.use('../mplstyles/stylelib/standard.mplstyle')

#other computational libraries
import numpy as np
import pandas as pd
import scipy
import scipy.constants as co
import scipy.stats as ss
import itertools
import pickle

In [2]:
coindata1 = pd.read_csv("data/r76_roi_events_trig_set1.txt", skiprows=3, engine='python',skipfooter=1,sep="*",skipinitialspace=True, \
            index_col=False, \
            names=['garbage','Row','SeriesNumber','EventNumber','pt_keVee','coinwin','PTOFdelay','zip4.PAWKmax','zip4.PAWKr50','cchisq'], \
            delim_whitespace=False)
coindata2 = pd.read_csv("data/r76_roi_events_trig_set2.txt", skiprows=3, engine='python',skipfooter=1,sep="*",skipinitialspace=True, \
            index_col=False, \
            names=['garbage','Row','SeriesNumber','EventNumber','pt_keVee','coinwin','PTOFdelay','zip4.PAWKmax','zip4.PAWKr50','cchisq'], \
            delim_whitespace=False)
coindata3 = pd.read_csv("data/r76_roi_events_trig_set3.txt", skiprows=3, engine='python',skipfooter=1,sep="*",skipinitialspace=True, \
            index_col=False, \
            names=['garbage','Row','SeriesNumber','EventNumber','pt_keVee','coinwin','PTOFdelay','zip4.PAWKmax','zip4.PAWKr50','cchisq'], \
            delim_whitespace=False)
coindata4 = pd.read_csv("data/r76_roi_events_trig_set4.txt", skiprows=3, engine='python',skipfooter=1,sep="*",skipinitialspace=True, \
            index_col=False, \
            names=['garbage','Row','SeriesNumber','EventNumber','pt_keVee','coinwin','PTOFdelay','zip4.PAWKmax','zip4.PAWKr50','cchisq'], \
            delim_whitespace=False)
frames = [coindata1, coindata2, coindata3, coindata4]

coindata = pd.concat(frames)
print (coindata.head(10))
print (coindata.tail(10))

   garbage    Row  SeriesNumber  EventNumber  pt_keVee  coinwin  PTOFdelay  \
0      NaN   6107   72209162200        70265  0.035493        0   0.000059   
1      NaN  40145   72209162200       430871  0.099517        1   0.000016   
2      NaN  40417   72209162200       440254  0.045830        0   0.000039   
3      NaN  44615   72209162200       480783  0.036227        0   0.000034   
4      NaN  45533   72209162200       490759  0.260436        0   0.000034   
5      NaN  48298   72209162200       520788  0.035016        0   0.000045   
6      NaN  54136   72209162200       590105  0.505874        0   0.000046   
7      NaN  55791   72209162200       600805  0.085282        0   0.000058   
8      NaN  60164   72209162200       650562  0.035801        0   0.000054   
9      NaN  64728   72209162200       700360  0.036148        0   0.000048   

   zip4.PAWKmax  zip4.PAWKr50  cchisq  
0  8.242765e-07      0.000401       1  
1  8.271136e-07      0.000406       1  
2  8.102761e-07      

In [3]:
print(np.shape(coindata))

(2321, 10)


In [4]:
series = np.asarray(coindata['SeriesNumber'])
ev = np.asarray(coindata['EventNumber'])
EkeV = np.asarray(coindata['pt_keVee'])
ccoinwin = np.asarray(coindata['coinwin'],dtype=np.dtype(bool))
cchisq = np.asarray(coindata['cchisq'],dtype=np.dtype(bool))

In [5]:
print(np.sum((EkeV>0.1)&cchisq))
print(np.sum((EkeV>0.1)&~cchisq))

128
141


In [6]:
csiggood = (EkeV>0.1)&cchisq
csigbad  = (EkeV>0.1)&~cchisq

In [7]:
print(series[csiggood])
print(ev[csiggood])

[72209162200 72209162200 72209162200 72209162200 72209162200 72209162200
 72209162200 72209162200 72209162200 72209162200 72209171225 72209171225
 72209171225 72209171225 72209171225 72209171225 72209171225 72209171225
 72209172155 72209172155 72208301829 72208301829 72208301829 72208302118
 72208302118 72208302118 72208302118 72208302118 72208302118 72208302118
 72208302118 72208302118 72208302118 72208302118 72208302118 72208302118
 72208302118 72208302118 72208302118 72208302118 72208302118 72208311151
 72208311151 72208311151 72208311151 72208311151 72208311151 72210191832
 72210191832 72210191832 72210191832 72210191832 72210191832 72210191832
 72210191832 72210191832 72210192240 72210192240 72210192240 72210192240
 72210192240 72210192240 72210192240 72210192240 72210192240 72210192240
 72210192240 72210192240 72210192240 72210192240 72210192240 72210192240
 72210192240 72210192240 72210192240 72210192240 72210192240 72210192240
 72210192240 72210192240 72210192240 72210192240 72

In [8]:
print(ev)

[  70265  430871  440254 ... 3501309 3521382 3530177]


In [9]:
print(series[csigbad])
print(ev[csigbad])

[72209162200 72209162200 72208302118 72208302118 72208302118 72208302118
 72208302118 72208302118 72208311151 72208311151 72208311151 72208311151
 72208311151 72208311151 72208311151 72208311151 72208311151 72208311151
 72208311151 72208311151 72210191832 72210191832 72210191832 72210191832
 72210192240 72210192240 72210192240 72210192240 72210192240 72210192240
 72210192240 72210192240 72210192240 72210192240 72210192240 72210192240
 72210192240 72210200954 72210200954 72210200954 72210200954 72210200954
 72210200954 72210200954 72210200954 72210200954 72210200954 72210200954
 72210200954 72210200954 72210200954 72210200954 72210200954 72210200954
 72210200954 72210200954 72210200954 72210200954 72210200954 72210200954
 72210200954 72210200954 72210200954 72210251956 72210251956 72210251956
 72210251956 72210251956 72210251956 72210251956 72210251956 72210251956
 72210261049 72210261049 72210261049 72210261049 72210261049 72210261049
 72210261049 72210261049 72210261049 72210261049 72

In [10]:
with open('data/r76-80V-naitrig-100eV-goodchi.txt', 'w') as f:
    for i,s in enumerate(series):
        if(csiggood[i]):
          f.write('{} {}\n'.format(s,ev[i]))

In [11]:
with open('data/r76-80V-naitrig-100eV-badchi.txt', 'w') as f:
    for i,s in enumerate(series):
        if(csigbad[i]):
          f.write('{} {}\n'.format(s,ev[i]))

In [12]:
print(np.unique(series[csiggood]))

[72208301829 72208302118 72208311151 72209162200 72209171225 72209172155
 72210191832 72210192240 72210200954 72210251956 72210261049 72210262224
 72210270959]


In [14]:
useriesgood = np.unique(series[csiggood])

for s in useriesgood:
    scut = series[csiggood]
    ecut = ev[csiggood]
    cseries=(scut==s)
    print(ecut[cseries])

[550152 610538 620687]
[  70193  340676  530225  580726  920658 1220460 2520826 2560339 2690376
 3360712 3400635 3950868 4010638 4240150 5020188 6020421 6110497 6280605]
[1320198 1630263 1950136 2970369 3650606 3670094]
[ 490759  590105  970769  990193 1200805 1920692 2640676 3320285 3470461
 5310198]
[1500320 1970453 2280315 2920809 3240861 4530720 4950597 5080366]
[1220647 1520104]
[ 500590  680460 1000312 1000698 1430424 1560356 1640702 1690511 1931161]
[ 300587 1451328 1580294 1840013 2331140 2840178 3130642 3190005 3201271
 3351264 3580859 3620491 3681055 3881328 4000234 4281134 4500081 4530352
 4600667 4641222 4700336 4730824 4780158 4800447 4950275 4960824 5020230
 5030845 5211182 5231141]
[ 130138  151154  341350 1400017 2130450 2501291]
[1170399 1240596 1260361 1410567 1860893 2100878 2530769 2680223]
[  30702  560192  670320  791299 1320559 2260384 2390761 2450591 2570021]
[ 600726  730103  760402 1270453 1500097 1970500 2040316 2940172 3060908]
[ 471424  860507  940954 11612